name: booking_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  bloc: ^8.1.0
  buildcondition: ^0.0.4
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  freezed: ^2.1.0+1
  freezed_annotation: ^2.0.3
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_maps_flutter: ^2.2.0
  hexcolor: ^2.0.7
  image_picker: ^0.8.5+3
  internet_connection_checker: ^0.0.1+4
  json_annotation: ^4.6.0
  mit_x: ^1.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_sliders: ^20.2.50

dev_dependencies:
  build_runner: ^2.1.11
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
